name: CI

 on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

 env:
  BUILD_TYPE: Release

 jobs:
  build:
    runs-on: windows-latest

    steps:
    
    - name : Делаем pull
      uses: actions/checkout@v2
      
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Запускаем CMake
      run:  cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
         name: my-artifact
         path: hello.cpp
       
